server_list = [
    {'name': 'CSG',
     'url': 'http://www.coresoftwaregroup.com',
     'timeout': 300,
     'max_fails': 2,
     'assert_string': 'Based in Fort Collins, Colorado'},
    {'name': 'Elder Care',
     'url': 'http://www.eldercarenet.org',
     'timeout': 300,
     'max_fails': 2,
     'assert_string': 'The Elder Care Network Story'},
    {'name': 'Ohio',
     'url': 'http://www.ohiolegalservices.org',
     'timeout': 300,
     'max_fails': 2,
     'assert_string': 'For the Public'},
    {'name': 'MEC',
     'url': 'http://www.mec-math.org',
     'timeout': 300,
     'max_fails': 2,
     'assert_string': 'MEC'},
    {'name': 'Historic Hotels',
     'url': 'http://www.historic-hotels.com',
     'timeout': 300,
     'max_fails': 2,
     'assert_string': 'Historic Hotels of the Rockies'},
    {'name': 'Utah',
     'url': 'http://www.utahlegalservices.org',
     'timeout': 300,
     'max_fails': 2,
     'assert_string': 'Apply For Help Online Now'},
    {'name': 'Nagle Warren',
     'url': 'http://www.naglewarrenmansion.com',
     'timeout': 300,
     'max_fails': 2,
     'assert_string': 'Nagle Warren Mansion, Cheyenne, Wyoming'},
    {'name': 'Badger Law',
     'url': 'http://www.badgerlaw.net',
     'timeout': 300,
     'max_fails': 2,
     'assert_string': 'Welcome to BadgerLaw.net'},
    {'name': 'dermAdvocate',
     'url': 'http://www.dermadvocate.net',
     'timeout': 300,
     'max_fails': 2,
     'assert_string': 'dermAdvocate is ...'},
    {'name': 'NLADA',
     'url': 'http://www.nlada.org/Jobs',
     'timeout': 300,
     'max_fails': 2,
     'assert_string': 'NLADA'},
    {'name': 'NASAMS',
     'url': 'http://www.nasams.org',
     'timeout': 300,
     'max_fails': 2,
     'assert_string': 'Welcome to the National Alliance'},
    {'name': 'Kaivo',
     'url': 'http://www.kaivo.com',
     'timeout': 300,
     'max_fails': 2,
     'assert_string': 'Kaivo provides world class technology solutions'},
    {'name': 'Pellmans',
     'url': 'http://www.pellmans.org',
     'timeout': 300,
     'max_fails': 2,
     'assert_string': 'Automotive Soccer Club'},
    {'name': 'Ken Wilson',
     'url': 'http://www.kenwilson.org',
     'timeout': 300,
     'max_fails': 2,
     'assert_string': 'Ken Wilson'},
    {'name': 'Zephyr Self-Guided Adventures',
     'url': 'http://www.selfguidedadventures.com',
     'timeout': 300,
     'max_fails': 2,
     'assert_string': 'Zephyr Self-Guided Adventures'},
    {'name': 'Foundation on Aging for Larimer County',
     'url': 'http://www.foalarimer.org',
     'timeout': 300,
     'max_fails': 2,
     'assert_string': 'Foundation on Aging for Larimer County'},
    {'name': 'Colorado DECSYS',
     'url': 'http://colorado.decsys.us',
     'timeout': 300,
     'max_fails': 2,
     'assert_string': 'Drug Endangered Children Tracking System'},
    {'name': 'Nevada DECSYS',
     'url': 'http://nevada.decsys.us',
     'timeout': 300,
     'max_fails': 2,
     'assert_string': 'Drug Endangered Children Tracking System'},
    {'name': 'West Virginia DECSYS',
     'url': 'http://westvirginia.decsys.us',
     'timeout': 300,
     'max_fails': 2,
     'assert_string': 'Drug Endangered Children Tracking System'},
    {'name': 'Tennesee DECSYS',
     'url': 'http://tennesee.decsys.us',
     'timeout': 300,
     'max_fails': 2,
     'assert_string': 'Drug Endangered Children Tracking System'},
    {'name': 'Top Shop',
     'url': 'http://www.thetopshopkc.com',
     'timeout': 300,
     'max_fails': 2,
     'assert_string': 'Welcome to The Top Shop'},
    {'name': 'R & A Enterprises',
     'url': 'http://www.raelectric.com',
     'timeout': 300,
     'max_fails': 2,
     'assert_string': 'R & A Enterprises'},
    {'name': 'Colorado Dude & Guest Ranch Association',
     'url': 'http://www.coloradoranch.com',
     'timeout': 300,
     'max_fails': 2,
     'assert_string': 'Colorado Dude & Guest Ranch Association'},
    {'name': 'Clay County',
     'url': 'http://www.claycountygov.com',
     'timeout': 300,
     'max_fails': 2,
     'assert_string': 'Welcome to Clay County'},
    {'name': 'NanoScienceWorks',
     'url': 'http://www.nanoscienceworks.org',
     'timeout': 300,
     'max_fails': 2,
     'assert_string': 'NanoScienceWorks'},
    {'name': 'Clay County Sports',
     'url': 'http://sports.claycountygov.com',
     'timeout': 300,
     'max_fails': 2,
     'assert_string': 'Clay County Sports'},
    {'name': 'Harkins Eye Clinic',
     'url': 'http://www.harkinseyeclinic.com',
     'timeout': 300,
     'max_fails': 2,
     'assert_string': 'Harkins Eye Clinic'},
    {'name': 'NNRG',
     'url': 'http://www.nnrg.org',
     'timeout': 300,
     'max_fails': 2,
     'assert_string': 'NNRG'},
    {'name': 'Callahan Pool',
     'url': 'http://www.callahanpool.com',
     'timeout': 300,
     'max_fails': 2,
     'assert_string': 'Callahan Pool'},
    {'name': 'PRCA',
     'url': 'http://www.prcainfo.org',
     'timeout': 300,
     'max_fails': 2,
     'assert_string': 'PRCA'},
    {'name': 'Water Works Sports',
     'url': 'http://www.waterworkssportsmaui.com',
     'timeout': 300,
     'max_fails': 2,
     'assert_string': 'Water Works Sports'},
    {'name': 'C&E Lockbox',
     'url': 'http://celockbox.com',
     'timeout': 300,
     'max_fails': 2,
     'assert_string': 'Lockbox'},
    {'name': 'C&E Lockbox Condo Pay',
     'url': 'http://cecondopay.com',
     'timeout': 300,
     'max_fails': 2,
     'assert_string': 'Lockbox Condo Pay'},
    {'name': 'Intermountain Yearly Meeting',
     'url': 'http://imym.org',
     'timeout': 300,
     'max_fails': 2,
     'assert_string': 'Intermountain Yearly Meeting'},
    {'name': 'Santa Fe Monthly Meeting',
     'url': 'http://sf.imym.org',
     'timeout': 300,
     'max_fails': 2,
     'assert_string': 'Santa Fe Monthly Meeting'},
    {'name': 'Durango Friends Meeting',
     'url': 'http://durangoquakers.org',
     'timeout': 300,
     'max_fails': 2,
     'assert_string': 'Durango Friends Meeting'},
    {'name': 'HIRE A MOUNTAIN GUIDE',
     'url': 'http://www.hireamountainguide.com',
     'timeout': 300,
     'max_fails': 2,
     'assert_string': 'Climb'}
]
